//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easpnet.UrlRewrite.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easpnet.UrlRewrite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Addresses are not of the same type. 的本地化字符串。
        /// </summary>
        internal static string AddressesNotOfSameType {
            get {
                return ResourceManager.GetString("AddressesNotOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly name is required. 的本地化字符串。
        /// </summary>
        internal static string AssemblyNameRequired {
            get {
                return ResourceManager.GetString("AssemblyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;{0}&apos; is not allowed. 的本地化字符串。
        /// </summary>
        internal static string AttributeNotAllowed {
            get {
                return ResourceManager.GetString("AttributeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;{0}&apos; is required. 的本地化字符串。
        /// </summary>
        internal static string AttributeRequired {
            get {
                return ResourceManager.GetString("AttributeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calling error handler. 的本地化字符串。
        /// </summary>
        internal static string CallingErrorHandler {
            get {
                return ResourceManager.GetString("CallingErrorHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; element does not allow attributes. 的本地化字符串。
        /// </summary>
        internal static string ElementNoAttributes {
            get {
                return ResourceManager.GetString("ElementNoAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; element does not allow nested elements. 的本地化字符串。
        /// </summary>
        internal static string ElementNoElements {
            get {
                return ResourceManager.GetString("ElementNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The element &apos;{0}&apos; is not allowed. 的本地化字符串。
        /// </summary>
        internal static string ElementNotAllowed {
            get {
                return ResourceManager.GetString("ElementNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full type name must include assembly name. 的本地化字符串。
        /// </summary>
        internal static string FullTypeNameRequiresAssemblyName {
            get {
                return ResourceManager.GetString("FullTypeNameRequiresAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input is not hex. 的本地化字符串。
        /// </summary>
        internal static string InputIsNotHex {
            get {
                return ResourceManager.GetString("InputIsNotHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type is specified does not support the required interface. 的本地化字符串。
        /// </summary>
        internal static string InvalidTypeSpecified {
            get {
                return ResourceManager.GetString("InvalidTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map &apos;{0}&apos; has already been defined. 的本地化字符串。
        /// </summary>
        internal static string MapAlreadyDefined {
            get {
                return ResourceManager.GetString("MapAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapped values are not allowed if a mapper type is specified. 的本地化字符串。
        /// </summary>
        internal static string MappedValuesNotAllowed {
            get {
                return ResourceManager.GetString("MappedValuesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Easpnet.UrlRewrite {0} 的本地化字符串。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redirecting &apos;{0}&apos; to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RedirectingXtoY {
            get {
                return ResourceManager.GetString("RedirectingXtoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restarting because of rule. 的本地化字符串。
        /// </summary>
        internal static string RestartingBecauseOfRule {
            get {
                return ResourceManager.GetString("RestartingBecauseOfRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string ResultNotFound {
            get {
                return ResourceManager.GetString("ResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rewriting &apos;{0}&apos; to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RewritingXtoY {
            get {
                return ResourceManager.GetString("RewritingXtoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping because of rule. 的本地化字符串。
        /// </summary>
        internal static string StoppingBecauseOfRule {
            get {
                return ResourceManager.GetString("StoppingBecauseOfRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 As configured, the rules caused too many restarts.  Please review your rewriting rules and ensure there are no infinite loops. 的本地化字符串。
        /// </summary>
        internal static string TooManyRestarts {
            get {
                return ResourceManager.GetString("TooManyRestarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type name is required. 的本地化字符串。
        /// </summary>
        internal static string TypeNameRequired {
            get {
                return ResourceManager.GetString("TypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; of the processing attribute is invalid.  It must be either &apos;{1}&apos;, &apos;{2}&apos; or &apos;{3}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ValueOfProcessingAttribute {
            get {
                return ResourceManager.GetString("ValueOfProcessingAttribute", resourceCulture);
            }
        }
    }
}
